title: "Amoolya Srinivasa"
description: "Bioinformatics Programmer at NYU Langone Health"
keywords: "Bioinformatics, Computational Biology, Machine Learning, Genomics"
author: "Amoolya Srinivasa"
baseurl: ""
url: "https://amoolyasrinivasa.github.io"

markdown: kramdown
highlighter: rouge
permalink: /:title/

name: "Amoolya Srinivasa"
picture: "assets/images/Amoolya.jpg"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _legacy_theme

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      projects: true
